include $(GNUSTEP_MAKEFILES)/common.make

VERSION = 0.1
PACKAGE_NAME = AnyPod
APP_NAME = AnyPod
SDUNIX_APPLICATION_ICON = Resources/icon.png

AnyPod_OBJC_FILES = \
	main.m

include $(GNUSTEP_MAKEFILES)/application.make
